-- SQL para crear la tabla de resultados DISC

CREATE TABLE public."DISC" (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  user_name text,
  time_taken_seconds integer,
  d_score integer,
  i_score integer,
  s_score integer,
  c_score integer,
  profile_code text,      -- Ejemplo: "DI", "SC"
  primary_style text,     -- Estilo dominante
  secondary_style text,   -- Estilo secundario
  -- Almacenamos todas las respuestas en formato JSON para análisis detallado
  answers jsonb,          
  
  -- Campos opcionales si prefieres columnas individuales para cada pregunta
  q1_plus text, q1_minus text,
  q2_plus text, q2_minus text,
  q3_plus text, q3_minus text,
  q4_plus text, q4_minus text,
  q5_plus text, q5_minus text,
  q6_plus text, q6_minus text,
  q7_plus text, q7_minus text,
  q8_plus text, q8_minus text,
  q9_plus text, q9_minus text,
  q10_plus text, q10_minus text,
  q11_plus text, q11_minus text,
  q12_plus text, q12_minus text,
  q13_plus text, q13_minus text,
  q14_plus text, q14_minus text,
  q15_plus text, q15_minus text,
  q16_plus text, q16_minus text,
  q17_plus text, q17_minus text,
  q18_plus text, q18_minus text,
  q19_plus text, q19_minus text,
  q20_plus text, q20_minus text,
  q21_plus text, q21_minus text,
  q22_plus text, q22_minus text,
  q23_plus text, q23_minus text,
  q24_plus text, q24_minus text
);

-- Habilitar seguridad de nivel de fila (RLS)
ALTER TABLE public."DISC" ENABLE ROW LEVEL SECURITY;

-- Crear política de inserción pública (ajustar según necesidad)
CREATE POLICY "Permitir inserción pública" 
ON public."DISC" 
FOR INSERT 
WITH CHECK (true);

-- Crear política de lectura pública
CREATE POLICY "Permitir lectura pública" 
ON public."DISC" 
FOR SELECT 
USING (true);
